project:
  type: book
  output-dir: docs

book:
  title: "医学与生物统计学"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: descriptive_statistics.qmd
      chapters:
        - quantitative_data.qmd
        - qualitative_data.qmd

    - part: "概率论与数理统计"
      chapters:
        - probability_theory.qmd
        - SamplingDistribution.qmd
        - ParameterEstimation.qmd
        - hypothesis_test.qmd
        - normality_test.qmd
        - variance_homogeneity_test.qmd
        - t_test.qmd
        - rate_proportion_test.qmd
        - ANOVA.qmd
        - repeated_measures_ANOVA.qmd
        - chi-square_test.qmd
        - nonparametric_test.qmd
        - correlation.qmd
        

    #     - PowerAnalysis.qmd
    #     - Causal_Inference.qmd
    - part: "统计模型"
      chapters:
        - LinearRegression.qmd
        - GLM.qmd
        - LME.qmd
        - GEE.qmd


    - part: "生存分析"
      chapters:
        - SurvivalAnalysis.qmd

    - part: "倾向性评分"
      chapters:
        - PropensityScore.qmd
   


    - part: "研究设计"
      chapters: 
        - diagnostic_test.qmd
        - observational_study_design.qmd

        

execute:
  cache: true
  message: false
  warning: false
  
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
crossref: 
  fig-title: 图
  fig-prefix: 图
  tbl-title: 表
  tbl-prefix: 表
  
format: 
  html: 
    theme: cosmo
    css: styles.css
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: mathjax

    
editor: visual


