project:
  type: book
  output-dir: docs

book:
  title: "医学与生物统计学"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: descriptive_statistics.qmd
      chapters:
        - quantitative_data.qmd
        - qualitative_data.qmd
        - correlation.qmd
        
    - part: hypothesis_test.qmd
      chapters:
      #   - probability_theory.qmd
      #   - SamplingDistribution.qmd
      #   - ParameterEstimation.qmd
        - normality_test.qmd
        - variance_homogeneity_test.qmd
        
        - t_test.qmd
        - ANOVA.qmd
        - repeated_measures_anova.qmd
        
        - proportion_test.qmd
        - chi-square_test.qmd
        - nonparametric_test.qmd
       
    #     - PowerAnalysis.qmd
    #     - Causal_Inference.qmd
    - part: "统计模型"
      chapters:
        - simple_linear_regression.qmd
        - multiple_linear_regression.qmd
        - LME.qmd
        - GLM.qmd
        - GEE.qmd

    - part: "生存分析"
      chapters:
        - SurvivalAnalysis.qmd
        - CoxProportionalHazardsModel.qmd
        - CompetingRiskModel.qmd

    - part: "临床研究设计"
      chapters: 
        - diagnostic_test.qmd
        # - observational_study_design.qmd
        - RCT.qmd

        

execute:
  message: false
  warning: false
  
toc: true
toc-depth: 4
toc-location: right
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE

date-modified: today

code-fold: show
code-link: true
code-summary: "Show the code"

css: style.css

format: html
theme:
  dark: darkly # 深色模式
  light: flatly
    
editor: visual


